### ISSUE TITLE
Unexpected token =

### ISSUE THREAD

**Issue by mthooyavan** [yeojz/otplib#43]
I am getting the below error on adding otplib to my project through npm

/home/thooyavan/api/node_modules/otplib/hotp.js:21
  set options(opt = {}) {
                  ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Module._extensions..js (module.js:417:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/thooyavan/api/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/thooyavan/api/node_modules/otplib/otplib.js:14:28)
    at Module._compile (module.js:410:26)

Someone Kindly help me out

**Comment by mthooyavan** [comment]
Hi,

Sorry its fixed now after updating the node.

Thank you,
—————————————————————————————————
Thooyavan Manivaasakar,
Bangalore.

mail@thooyavan.me
(+91) 995-248-8880


CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use , disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message(S).

**Comment by yeojz** [comment]
Cool. That's great!
