### ISSUE TITLE
Default secret length should be changed to 20 bytes from 10 bytes

### ISSUE THREAD

**Issue by nflaig** [yeojz/otplib#671]
Currently, the secret generation using the [default value of 10 bytes](https://github.com/yeojz/otplib/blob/master/packages/otplib-core/src/authenticator.ts#L265) is not compliant with the requirements mentioned in [RFC 4226 section 4](https://datatracker.ietf.org/doc/html/rfc4226#section-4).

> R6 - The algorithm MUST use a strong shared secret.  The length of
   the shared secret MUST be at least 128 bits.  This document
   RECOMMENDs a shared secret length of 160 bits.

It clearly states that it MUST be at least 128 bits which means using the default value of this library is non compliant.

I suggest that the default value is at least increased to 16 bytes or better follow the recommended value of 20 bytes (160 bits) as mentioned in RFC 4226.

Related:
- [Google Authenticator PAM module issue](https://github.com/google/google-authenticator-libpam/issues/18)
- [Google Authenticator issue](https://github.com/google/google-authenticator/issues/339)
- [Security Stack Exchange post](https://security.stackexchange.com/questions/45053/why-does-google-cripple-the-2fa-google-authenticator-pam-module)

**Comment by disconnect3d** [comment]
FWIW this issue or vulnerability was introduced in 12.0.0. Old versions of otplib used 20 bytes for OTP secret generation.

See:
* https://github.com/yeojz/otplib/blob/v11.0.1/packages/otplib-authenticator/Authenticator.js#L82-L96

Vs:
* https://github.com/yeojz/otplib/blob/v12.0.0/packages/otplib-core/src/authenticator.ts#L262-L267

Why was this changed at all?

**Comment by D0han** [comment]
This changed exactly in https://github.com/yeojz/otplib/commit/b088efe9da45e102e59b5cd2c0df5bddf80c5a92
@yeojz seems that you committed that change, can you shed some light here?

**Comment by disconnect3d** [comment]
For what is worth, the old version of the lib also has a quirk which is a bug I think.

If you look over how its secret key is generated:
https://github.com/yeojz/otplib/blob/dd7dc73ee08032df0196d8774b55af210b27cab5/packages/otplib-utils/secretKey.js#L10-L23

It turns out that the default 20 bytes of entropy are only 15 bytes of entropy in practice, because of the `.slice(0, length)` operation.

This can be seen below in a `node` REPL session:
```js
> entropy = crypto.randomBytes(20)
<Buffer 45 07 a2 bc 59 e7 cc 29 be 06 0b 16 d1 b8 bb 8e 5c ed a7 92>
> encoded = entropy.toString('base64')
'RQeivFnnzCm+BgsW0bi7jlztp5I='
> encoded.length
28
> sliced = encoded.slice(0, 20)
'RQeivFnnzCm+BgsW0bi7'
> sliced.length
20
> buffer = Buffer.from(sliced, 'base64')
<Buffer 45 07 a2 bc 59 e7 cc 29 be 06 0b 16 d1 b8 bb>
> buffer.length
15
```

So the old version defaults gives only 15 bytes of entropy which is 120 bits which is under the "MUST" value and definetely below the "RECOMMENDED" one.

**Comment by yeojz** [comment]
As part of v13.x rewrite, this has been addressed. 
By default it is set to 20 bytes, and the weird generation logic is removed (not sure why I did that).

**Comment by nktnet1** [comment]
When extracting the secret from QR code provided by many 3rd party sites for use in automation, we often get a secret like

```
3HOSCSDJ5FO3ZQS7
```

Using this secret with the `generate` function with default options will result in the error:

```
/my-project/node_modules/.pnpm/@otplib+core@13.4.0/node_modules/@otplib/core/src/utils.ts:321
    throw new SecretTooShortError(guardrails.MIN_SECRET_BYTES, secret.length);
          ^

h [SecretTooShortError]: Secret must be at least 16 bytes (128 bits), got 10 bytes
    at Or (/my-project/node_modules/.pnpm/@otplib+core@13.4.0/node_modules/@otplib/core/src/utils.ts:321:11)
    at getTOTPGenerateOptions (/my-project/node_modules/.pnpm/@otplib+totp@13.4.0/node_modules/@otplib/totp/src/index.ts:75:3)
    at b (/my-project/node_modules/.pnpm/@otplib+totp@13.4.0/node_modules/@otplib/totp/src/index.ts:129:15)
    at Object.totp (/my-project/node_modules/.pnpm/otplib@13.4.0/node_modules/otplib/src/functional.ts:225:7)
    at executeByStrategy (/my-project/node_modules/.pnpm/otplib@13.4.0/node_modules/otplib/src/functional.ts:43:21)
    at m (/my-project/node_modules/.pnpm/otplib@13.4.0/node_modules/otplib/src/functional.ts:223:10)
    at <anonymous> (/my-project/src/utils/totp.ts:13:22)
    at ModuleJob.run (node:internal/modules/esm/module_job:437:25)
    at async node:internal/modules/esm/loader:639:26
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)

Node.js v24.15.0
```

I think it would help if the docs could be clearer about how this can be fixed.

The [v13.0.0](https://github.com/yeojz/otplib/releases/tag/v13.0.0) changelog should also explicitly state this as a breaking change if you are updating from a previous version instead of a fresh deploy.

The workaround I ultimatedly found was what you wrote here:

- https://github.com/yeojz/otplib/issues/752#issuecomment-3794769293

i.e. passing `guardrails`:

```ts
import { createGuardrails, generate } from "otplib";

const secret = "3HOSCSDJ5FO3ZQS7";

const code = await generate({
  secret,
  guardrails: createGuardrails({
    MIN_SECRET_BYTES: 10,
  }),
});

console.log({ code });
```
